---
- name: Permit HTTP traffic
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  become: true
  become_user: root

- name: Permit HTTPS traffic
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
  become: true
  become_user: root

- name: Permit API traffic
  ansible.posix.firewalld:
    service: kube-apiserver
    permanent: true
    state: enabled
  become: true
  become_user: root
